### ISSUE TITLE
Ajustement section ''MORE THAN COMMUNITY"

### ISSUE THREAD

**Issue by Belooh** [Techzara/techzara-site#9]
![image](https://user-images.githubusercontent.com/36695755/65696254-92cfb680-e081-11e9-9696-85a1f23153e3.png)
Proposition: 
- titre à corriger: "MORE THAN A COMMUNITY"
- Texte: 
TechZara is like a second familly, a sweet home for developpers, geeks, passionates of computer science, professionals and students .
We offer more opportunities, share knowledge, experience and much more funny moments.

**Comment by julkwel** [comment]
Fix in #f9db83f
